[project]
name = "parnassus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
  {name = "Dmitrii Kobylianskii", email = "dmitry.kobylyansky@weizmann.ac.il"},
]
license = "MIT"
requires-python = ">=3.12, <3.13"
dependencies = [
    "energyflow>=1.4.0",
    "fastjet>=3.4.3.1",
    "numpy",
    "particle>=0.25.2",
    "pyhepmc>=2.14.0",
    "rich>=13.9.4",
    "torch>=2.6.0",
    "uproot>=5.5.2, <5.6.7",
    "pyyaml",
    "joblib",
    "pythia8mc==8.316.0"
]

[project.scripts]
parnassus = "parnassus.main:main"
fast-eval = "parnassus.fast_eval:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
reportAny=false
reportExplicitAny=false
reportImplicitStringConcatenation=false

[tool.ruff]
line-length = 100
preview = true
lint.select = ["ALL"]
lint.ignore = [
  "COM", "D100", "D102", "D105", "D205", "D401", "EM", "FIX", "FBT",
  "S101", "S404", "S602", "PLR2004", "PLR0912", "PLR0914", "CPY001", "TRY003",
  "G004", "N802", "C901", "DTZ005", "DTZ007", "INP", "EXE002",
  "ANN001", "ANN002", "ANN003", "ANN201", "ANN202", "ANN204",
  "T201", "PLW1514", "PTH123", "RUF017", "PLR6301", "ISC001", "S307",
  "PT027", "NPY002", "PT009", "PLW1641", "PLR0904", "N817", "S603", "PD011",
  "S113", "TCH", "PT011", "PLR1702", "S108", "PTH207", "S607", "E203", "SIM115", "PLR0913",
  "PLR0917", "A005", "ANN401", "PLR0915", "RUF015", "PLR6104", "TD002", "TD003",
]


[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff.lint.flake8-builtins]
builtins-allowed-modules = ["typing"]

[tool.mypy]
exclude = "parnassus/models/modules"
[[tool.mypy.overrides]]
module = ['awkward', 'uproot']
ignore_missing_imports = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "CRITICAL"
filterwarnings = ["ignore::DeprecationWarning"]

[dependency-groups]
dev = [
    "basedpyright>=1.27.1",
    "coverage>=7.7.1",
    "ipykernel>=6.29.5",
    "ipython>=8.32.0",
    "mypy==1.18.2",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "ruff==0.14.6",
    "types-pyyaml>=6.0.12.20250402",
    "matplotlib",
    "tqdm",
    "scipy",
    "gdown",
]
