"""TorchDelphes Validation Test Suite.

Processes HepMC files through TorchDelphes and validates output against
C++ Delphes benchmarks. Generates comparison histograms for all output
branches to verify implementation correctness.

Supported detectors:
    - CMS: Uses delphes_card_CMS_6_1.tcl configuration
    - ATLAS: Uses delphes_card_ATLAS_6_1.tcl configuration

Processing pipeline:
    1. Load HepMC events and convert to tensor format
    2. Apply detector simulation (CMSEnergyFlowDefault or ATLASEnergyFlowDefault)
    3. Write output to ROOT file in Delphes format
    4. Generate validation histograms comparing to C++ Delphes benchmark

Usage:
    # Process 1000 events with CMS detector
    python test_torch_delphes.py --detector CMS --num-events 1000 --debug

    # Process with ATLAS detector
    python test_torch_delphes.py --detector ATLAS --num-events 1000 --debug

    # Skip generation, only run validation
    python test_torch_delphes.py --skip-gen --detector CMS

Output files:
    - ROOT file: {process}_{nevents}_6_1_torch.root
    - Validation plots: torch_delphes_validation/{process}/{detector}/

Required benchmark files:
    - delphes_data/{process}/{detector}/{process}_{nevents}_6_1.root
      (Generated by C++ Delphes with corresponding TCL card)
"""

import argparse
import random
import time
from pathlib import Path

import numpy as np
import torch
from tqdm import tqdm

# Set PyTorch to use maximum precision (double precision / float64)
# torch.set_default_dtype(torch.float64)

# Seeds for reproducibility
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

from parnassus.pipelines.torch_delphes import write_torch_delphes_output
from parnassus.torch_delphes.defaults import ATLASEnergyFlowDefault, CMSEnergyFlowDefault
from parnassus.torch_delphes.tensor_utils import (
    ColumnMap,
    hepmc_to_tensor,
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")


def main(
    input_file: str,
    output_file: str,
    detector: str,
) -> None:
    """Main processing function.

    Args:
        input_file: Path to input HepMC file
        output_file: Path to output ROOT file
        benchmark_file: Path to benchmark ROOT file
        max_events: Maximum number of events to process (None = all)
        batch_size: Number of events to process per batch (for GPU acceleration)
        debug: If True, print histogram bin counts and edges for debugging
    """
    n_events = 100
    batch_size = 1_000_000  # particles, not events
    print("\n" + "=" * 80)
    print("Parnassus.TorchDelphes Processing")
    print("=" * 80)
    print(f"\nInput:  {input_file}")
    print(f"Batch size: {batch_size}")
    print(f"Device: {DEVICE}")

    # ========================================================================
    # 1. Load HepMC and convert to tensors
    # ========================================================================
    print("\n" + "=" * 80)
    print(f"STEP 1: Loading HepMC file and converting to tensors: {input_file}")
    print("=" * 80)

    stable_particles, all_particles = hepmc_to_tensor(input_file, n_events)
    stable_particles = stable_particles.to(DEVICE)
    all_particles = all_particles.to(DEVICE)

    n_event = len(torch.unique(stable_particles[:, ColumnMap.EVENT_NUMBER]))
    n_part_total = stable_particles.shape[0]
    n_all_particles = all_particles.shape[0]
    print(f"Loaded {n_event} events from HepMC")
    print(f"  Total stable particles: {n_part_total}")
    print(f"  Total all particles (including unstable): {n_all_particles}")

    # ========================================================================
    # 2. Apply CMSModule
    # ========================================================================
    print("\n" + "=" * 80)
    print("STEP 2: Applying Detector Module...")
    print("=" * 80)

    if detector == "CMS":
        print("Using module: CMSEnergyFlowDefault")
        torch_detector = CMSEnergyFlowDefault(debug=False).to(DEVICE)
    elif detector == "ATLAS":
        print("Using module: ATLASDefault")
        torch_detector = ATLASEnergyFlowDefault(debug=False).to(DEVICE)
    else:
        raise NotImplementedError(f"Detector {detector} not implemented. Choose 'CMS' or 'ATLAS'.")

    tic_torch = time.time()
    results = {}
    for batch_start in tqdm(range(0, n_part_total, batch_size)):
        batch_end = min(batch_start + batch_size, n_part_total)
        batch_particles = stable_particles[batch_start:batch_end]

        batch_results = torch_detector(batch_particles)

        for k, v in batch_results.items():
            if k not in results:
                results[k] = []
            results[k].append(v.cpu())

    toc_torch = time.time()
    dur_torch = toc_torch - tic_torch
    print(f"\nTorch processing time: {dur_torch // 60:.0f} minutes, {dur_torch % 60:.2f} seconds")

    # ========================================================================
    # 3. Write output
    # ========================================================================

    print(f"\nWriting {output_file}...")

    # Concatenate batched results
    for k, v in results.items():
        results[k] = torch.cat(v, dim=0)

    # Convert to ROOT format and write
    # tensor_to_root_dict expects List[Tensor], so wrap single tensors in a list
    write_torch_delphes_output(
        output_path=output_file, truth_tensor=all_particles, pflow_tensor=results["EFlowObject"]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Parnassus TorchDelphes HepMC Processing")
    parser.add_argument(
        "--process",
        "-proc",
        type=str,
        default="HZZ4l",
        choices=["HZZ4l"],
        help="Process to simulate (default: HZZ4l)",
    )
    parser.add_argument(
        "--detector",
        "-det",
        type=str,
        default="CMS",
        choices=["CMS", "ATLAS"],
        help="Detector configuration to use (default: CMS)",
    )
    return parser.parse_args()


def _get_paths(args, script_dir: Path) -> tuple[Path, Path, Path, Path]:
    data_process_dir = script_dir / "delphes_data" / args.process
    input_fpath = data_process_dir / f"{args.process}_100.hepmc"
    output_fpath = data_process_dir / f"{args.detector}" / f"{args.process}_100_torch.root"
    return input_fpath, output_fpath


if __name__ == "__main__":
    tic = time.time()
    args = parse_args()
    script_dir = Path(__file__).parent
    input_fpath, output_fpath = _get_paths(args, script_dir)

    main(input_fpath, output_fpath, detector=args.detector)

    toc = time.time()
    dur = toc - tic
    print(f"\n{'=' * 80}")
    print(f"Total execution time on {DEVICE}: {dur // 60:.0f} minutes, {dur % 60:.2f} seconds")
    print(f"{'=' * 80}\n")
