"""TorchDelphes Validation Test Suite.

Processes HepMC files through TorchDelphes and validates output against
C++ Delphes benchmarks. Generates comparison histograms for all output
branches to verify implementation correctness.

Supported detectors:
    - CMS: Uses delphes_cards/delphes_card_CMS_eflow.tcl configuration
    - ATLAS: Uses delphes_cards/delphes_card_ATLAS_eflow.tcl configuration

Processing pipeline:
    1. Load HepMC events via HepMCDataset + ParametricAdapter
    2. Apply detector simulation via ParametricEventGenerator
    3. Write output to ROOT file via RootWriter
    4. Generate validation histograms comparing to C++ Delphes benchmark

Usage:
    # Process 1000 events with CMS detector
    python validate_torch_delphes.py --detector CMS --num-events 1000 --debug

    # Process with ATLAS detector
    python validate_torch_delphes.py --detector ATLAS --num-events 1000

    # Skip generation, only run validation
    python validate_torch_delphes.py --skip-gen --detector CMS

Output files:
    - ROOT file: {process}_{nevents}_eflow_torch.root
    - Validation plots: validation_plots/{process}/{detector}/

Required benchmark files:
    - delphes_data/{process}/{detector}/{process}_{nevents}_eflow.root
      (Generated by C++ Delphes with corresponding TCL card)
"""

import argparse
import time
from pathlib import Path

import awkward as ak
import matplotlib.pyplot as plt
import numpy as np
import torch
import uproot
from torch.utils.data import DataLoader

from parnassus.configs.accessors import AccessorStore
from parnassus.configs.generators.parametric import ParametricGeneratorConfig
from parnassus.configs.writer import WriterConfig
from parnassus.data.adapters import ParametricAdapter, parametric_collate_fn
from parnassus.data.hepmc import HepMCDataset
from parnassus.pipelines.generators.parametric import ParametricEventGenerator
from parnassus.utils.logger import setup_logger
from parnassus.writers.root import RootWriter

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")


# MAP DICT

TORCH_MAP_DICT = {
    "Particle": "AllParticles",
    "Track": "Track",
    "Tower": "Tower",
    "EFlowObject": "Pflow",
}


def validate_against_benchmark(
    torch_output_file: str | Path,
    benchmark_file: str | Path,
    output_dir: str | Path,
    debug: bool = False,
    event_number: int | None = None,
    validate_pid: bool = False,
) -> None:
    """Validate TorchDelphes output against C++ Delphes benchmark.

    Generates side-by-side histogram comparisons for all relevant branches
    and kinematic variables. Histograms are saved as PNG files for visual
    inspection.

    Parameters
    ----------
        torch_output_file: Path to TorchDelphes output ROOT file
        benchmark_file: Path to C++ Delphes benchmark ROOT file
        output_dir: Directory to save validation plots
        debug: If True, validate additional intermediate branches
            (ParticleAfterProp, ChargedHadron, etc.)
        event_number: If specified, validate only this single event (0-indexed).
            Useful for debugging specific event discrepancies.
        validate_pid: If True, create PID-specific validation plots.
            Can be slow for datasets with many unique PIDs.

    Notes
    -----
        Creates PNG histogram files in output_dir:
        - kinematic_{branch}_{variable}.png: Per-variable histograms
        - validation_{branch}.png: Combined multi-variable plots
    """
    # Create output directory (with event subdirectory if single event)
    output_dir = Path(output_dir)
    if event_number is not None:
        output_dir = output_dir / f"event_{event_number}"
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'=' * 70}")
    if event_number is not None:
        print(f"Validating Event {event_number}")
    else:
        print("Validating All Events (Aggregated)")
    print(f"{'=' * 70}")

    print(f"PyTorch output: {torch_output_file}")
    torch_root = uproot.open(torch_output_file)
    torch_tree = torch_root["Parnassus"]

    print(f"C++ Delphes benchmark: {benchmark_file}")
    benchmark_root = uproot.open(benchmark_file)
    benchmark_tree = benchmark_root["Delphes"]
    print(f"Output directory: {output_dir}")

    # Check event bounds if validating single event
    if event_number is not None:
        sample_branch = "Track/Track.PT"
        torch_key = sample_branch.split("/", maxsplit=1)[0]
        torch_key = TORCH_MAP_DICT.get(torch_key, torch_key)  # Map to PyTorch branch name
        print(torch_tree.keys())
        if torch_key in torch_tree:
            n_events_torch = len(torch_tree[torch_key + ".PT"].array())  # pyright: ignore[reportAttributeAccessIssue]
            n_events_benchmark = len(benchmark_tree[sample_branch].array())  # pyright: ignore[reportAttributeAccessIssue]

            if event_number >= n_events_torch or event_number >= n_events_benchmark:
                raise ValueError(
                    f"Event index {event_number} out of range. "
                    f"PyTorch has {n_events_torch} events, "
                    f"C++ has {n_events_benchmark} events."
                )
            print(f"Event {event_number} / {min(n_events_torch, n_events_benchmark) - 1}")

    # Kinematic variables to compare
    # Track objects: PID, Charge, P, PT, Eta, Phi
    # Tower objects: E, ET, Eta, Phi, Eem, Ehad (no PID - towers are aggregated)
    # ParticleFlowCandidate: Combined Track+Tower fields
    # GenParticle: All HepMC particles including unstable
    track_kinematic_vars = [
        "PID",
        "Charge",
        "P",
        "PT",
        "Eta",
        "EtaOuter",
        "Phi",
        "T",
        "X",
        "Y",
        "Z",
    ]
    tower_kinematic_vars = ["E", "ET", "Eta", "Phi", "T"]
    eflow_kinematic_vars = [
        "PID",
        "Charge",
        "E",
        "P",
        "PT",
        "Eta",
        "Phi",
        "T",
        "X",
        "Y",
        "Z",
        "Eem",
        "Ehad",
    ]
    genparticle_kinematic_vars = [
        "PID",
        "Status",
        "Charge",
        "E",
        "Px",
        "Py",
        "Pz",
        "P",
        "PT",
        "Eta",
        "Phi",
        "Mass",
        "T",
        "X",
        "Y",
        "Z",
    ]

    # Branches to validate (branch_name, variable_list)
    if debug:
        branches = [
            ("Particle", genparticle_kinematic_vars),
            ("ParticleBeforeProp", track_kinematic_vars),
            ("ParticleAfterProp", track_kinematic_vars),
            ("ChargedHadron", track_kinematic_vars),
            ("Electron", track_kinematic_vars),
            ("Muon", track_kinematic_vars),
            ("NeutralParticle", track_kinematic_vars),
            ("ChargedHadronEfficiency", track_kinematic_vars),
            ("ElectronEfficiency", track_kinematic_vars),
            ("MuonEfficiency", track_kinematic_vars),
            ("ChargedHadronSmeared", track_kinematic_vars),
            ("ElectronSmeared", track_kinematic_vars),
            ("MuonSmeared", track_kinematic_vars),
            ("Track", track_kinematic_vars),
            ("ECalTower", tower_kinematic_vars),
            ("ECal_EFlowTrack", track_kinematic_vars),
            ("EFlowPhoton", tower_kinematic_vars),
            ("HCalTower", tower_kinematic_vars),
            ("EFlowTrack", track_kinematic_vars),
            ("EFlowNeutralHadron", tower_kinematic_vars),
            ("Tower", tower_kinematic_vars),
            ("EFlowObject", eflow_kinematic_vars),
        ]
    else:
        branches = [
            ("Particle", genparticle_kinematic_vars),
            ("Track", track_kinematic_vars),
            ("Tower", tower_kinematic_vars),
            ("EFlowTrack", track_kinematic_vars),
            ("EFlowPhoton", tower_kinematic_vars),
            ("EFlowNeutralHadron", tower_kinematic_vars),
            ("EFlowObject", eflow_kinematic_vars),
        ]

    print(f"\nValidating branches: {', '.join([b[0] for b in branches])}")

    for branch_name, kinematic_vars in branches:
        print(f"\n{'=' * 70}")
        print(f"Validating {branch_name}...")
        print(f"{'=' * 70}")

        # Create branch-specific directory
        branch_dir = output_dir / branch_name
        branch_dir.mkdir(exist_ok=True)

        # Check if branch exists in PyTorch output
        torch_branch_name = TORCH_MAP_DICT.get(branch_name, branch_name)
        torch_branch_keys = [k for k in torch_tree.keys() if k.startswith(f"{torch_branch_name}")]  # noqa: SIM118
        if not torch_branch_keys:
            print(f"  ⚠ {branch_name} not found in PyTorch output, skipping...")
            continue
        print(torch_branch_keys)
        # 1. Standalone plots for each kinematic variable
        for var in kinematic_vars:
            # Check if variable exists in both datasets
            torch_key = f"{torch_branch_name}.{var}"
            benchmark_key = f"{branch_name}/{branch_name}.{var}"

            if torch_key not in torch_tree:
                print(f"  ⚠ {var} not found in PyTorch {branch_name}, skipping...")
                continue

            if benchmark_key not in benchmark_tree:
                print(f"  ⚠ {var} not found in C++ {branch_name}, skipping...")
                continue

            try:
                # Load data from both sources
                torch_data_events = torch_tree[torch_key].array()  # pyright: ignore[reportAttributeAccessIssue]
                benchmark_data_events = benchmark_tree[benchmark_key].array()  # pyright: ignore[reportAttributeAccessIssue]

                # Handle single-event vs all-events mode
                if event_number is not None:
                    # Check event index bounds
                    if event_number >= len(torch_data_events) or event_number >= len(
                        benchmark_data_events
                    ):
                        print(f"  ⚠ Event {event_number} out of range for {var}, skipping...")
                        continue
                    # Extract single event data
                    torch_data = torch_data_events[event_number]
                    benchmark_data = benchmark_data_events[event_number]
                else:
                    # Flatten all events
                    torch_data = ak.flatten(torch_data_events)
                    benchmark_data = ak.flatten(benchmark_data_events)

                # Convert to numpy for plotting
                torch_np = np.asarray(torch_data)
                benchmark_np = np.asarray(benchmark_data)

                # Skip if both are empty (relevant for single-event mode)
                if len(torch_np) == 0 and len(benchmark_np) == 0:
                    print(f"  ⚠ No particles in {branch_name}.{var}, skipping...")
                    continue

                # Create figure with two subplots: histogram on top, ratio below
                fig = plt.figure(figsize=(10, 8))
                gs = fig.add_gridspec(2, 1, height_ratios=[3, 1], hspace=0.05)
                ax_hist = fig.add_subplot(gs[0])
                ax_ratio = fig.add_subplot(gs[1], sharex=ax_hist)

                width = 0.35
                # Special handling for PID: use discrete bins
                if var == "PID":
                    # Get unique PIDs across both datasets
                    unique_pids = np.unique(np.concatenate([torch_np, benchmark_np]))

                    # Count occurrences of each PID
                    torch_counts = np.array([np.sum(torch_np == pid) for pid in unique_pids])
                    benchmark_counts = np.array([
                        np.sum(benchmark_np == pid) for pid in unique_pids
                    ])

                    # Create bar positions
                    x = np.arange(len(unique_pids))
                    width = 0.35

                    # Plot bars
                    ax_hist.bar(
                        x - width / 2,
                        benchmark_counts,
                        width,
                        label="C++ Delphes",
                        color="orange",
                        alpha=0.7,
                    )
                    ax_hist.bar(
                        x + width / 2,
                        torch_counts,
                        width,
                        label="Parnassus.TorchDelphes",
                        color="blue",
                        alpha=0.7,
                    )

                    ax_hist.set_xticks(x)
                    ax_hist.set_xticklabels(
                        [f"{int(pid)}" for pid in unique_pids], rotation=45, ha="right"
                    )
                    ax_hist.tick_params(labelbottom=False)

                    # For ratio plot
                    bin_centers = x
                    ratio = np.divide(
                        torch_counts,
                        benchmark_counts,
                        out=np.ones_like(torch_counts, dtype=float),
                        where=benchmark_counts > 0,
                    )

                    ax_ratio.axhline(y=1.0, color="orange", linewidth=2)
                    ax_ratio.bar(bin_centers, ratio, width * 2, color="blue", alpha=0.7)
                    ax_ratio.set_xticks(bin_centers)
                    ax_ratio.set_xticklabels(
                        [f"{int(pid)}" for pid in unique_pids], rotation=45, ha="right"
                    )
                    ax_ratio.set_ylim(0.9 * min(ratio), 1.1 * max(ratio))  # Focus on ±10% range

                elif var in {"Charge", "Status"}:
                    # Charge and Status are discrete integer values - use bar chart like PID
                    # Get unique values across both datasets
                    unique_vals = np.unique(np.concatenate([torch_np, benchmark_np]))

                    # Count occurrences of each value
                    torch_counts = np.array([np.sum(torch_np == val) for val in unique_vals])
                    benchmark_counts = np.array([
                        np.sum(benchmark_np == val) for val in unique_vals
                    ])

                    # Create bar positions
                    x = np.arange(len(unique_vals))

                    # Plot bars
                    ax_hist.bar(
                        x - width / 2,
                        benchmark_counts,
                        width,
                        label="C++ Delphes",
                        color="orange",
                        alpha=0.7,
                    )
                    ax_hist.bar(
                        x + width / 2,
                        torch_counts,
                        width,
                        label="Parnassus.TorchDelphes",
                        color="blue",
                        alpha=0.7,
                    )

                    ax_hist.set_xticks(x)
                    ax_hist.set_xticklabels([f"{int(val)}" for val in unique_vals])
                    ax_hist.tick_params(labelbottom=False)

                    # For ratio plot
                    bin_centers = x
                    ratio = np.divide(
                        torch_counts,
                        benchmark_counts,
                        out=np.ones_like(torch_counts, dtype=float),
                        where=benchmark_counts > 0,
                    )

                    ax_ratio.axhline(y=1.0, color="orange", linewidth=2)
                    ax_ratio.bar(bin_centers, ratio, width * 2, color="blue", alpha=0.7)
                    ax_ratio.set_xticks(bin_centers)
                    ax_ratio.set_xticklabels([f"{int(val)}" for val in unique_vals])
                    ax_ratio.set_ylim(0.9 * min(ratio), 1.1 * max(ratio))  # Focus on ±10% range

                else:
                    # Standard continuous histogram
                    # Determine bin range
                    bins: int | list[float]
                    all_data = np.concatenate([torch_np, benchmark_np])
                    if len(all_data) > 0:
                        bins = list(
                            np.linspace(np.percentile(all_data, 1), np.percentile(all_data, 99), 50)
                        )
                    else:
                        bins = 50

                    # Plot histograms
                    benchmark_hist = ax_hist.hist(
                        benchmark_np,
                        bins=bins,
                        histtype="stepfilled",
                        color="orange",
                        alpha=0.5,
                        linewidth=2,
                        label="C++ Delphes",
                        density=False,
                    )
                    torch_hist = ax_hist.hist(
                        torch_np,
                        bins=bins,
                        histtype="step",
                        color="blue",
                        linewidth=2,
                        label="Parnassus.TorchDelphes",
                        density=False,
                    )
                    benchmark_counts = np.asarray(benchmark_hist[0])
                    bin_edges = np.asarray(benchmark_hist[1])
                    torch_counts = np.asarray(torch_hist[0])

                    # For ratio plot
                    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
                    ratio = np.divide(
                        torch_counts,
                        benchmark_counts,
                        out=np.ones_like(torch_counts),
                        where=benchmark_counts > 0,
                    )

                    # Line plot for continuous variables
                    ax_ratio.axhline(y=1.0, color="orange", linewidth=2)
                    ax_ratio.plot(bin_centers, ratio, color="blue", markersize=4, linewidth=2)
                    ax_ratio.set_ylim(0.9 * min(ratio), 1.1 * max(ratio))  # Focus on ±20% range

                ax_hist.set_ylabel("Counts", fontsize=12)
                title = f"{branch_name}: {var}"
                if event_number is not None:
                    title = f"Event {event_number}: {title}"
                ax_hist.set_title(title, fontsize=14, fontweight="bold")
                ax_hist.legend(fontsize=11)
                ax_hist.grid(True, alpha=0.3)
                if var not in {"PID", "Charge", "Status"}:
                    ax_hist.tick_params(labelbottom=False)  # Hide x-axis labels for top plot

                ax_ratio.set_xlabel(var, fontsize=12)
                ax_ratio.set_ylabel("Torch / C++", fontsize=10)
                ax_ratio.grid(True, alpha=0.3)

                # Add statistics text
                stats_text = (
                    f"PyTorch: {len(torch_np)} particles\n"
                    f"C++ Delphes: {len(benchmark_np)} particles"
                )
                ax_hist.text(
                    0.95,
                    0.95,
                    stats_text,
                    transform=ax_hist.transAxes,
                    fontsize=10,
                    verticalalignment="top",
                    horizontalalignment="right",
                    bbox={"boxstyle": "round", "facecolor": "wheat", "alpha": 0.5},
                )

                # Save plot
                plot_file = branch_dir / f"{var}.png"
                plt.tight_layout()
                plt.savefig(plot_file, dpi=150)
                plt.close()

                print(
                    f"  ✓ {var}: PyTorch={len(torch_np)}, "
                    f"C++={len(benchmark_np)} → {plot_file.name}"
                )

            except Exception as e:  # noqa: BLE001
                print(f"  ✗ {var}: Error - {e}")
                continue

        # 2. Combined plot with key kinematic variables
        # For GenParticle: Eta, Phi, PT, E
        # For tracks: Eta, Phi, PT, P
        # For towers: Eta, Phi, E, ET
        if branch_name == "Particle":
            combined_vars = ["Eta", "Phi", "PT", "E"]
            print("\n  Creating combined kinematic plot (Eta, Phi, PT, E)...")
        elif "P" in kinematic_vars and "E" not in kinematic_vars:
            combined_vars = ["Eta", "Phi", "PT", "P"]
            print("\n  Creating combined kinematic plot (Eta, Phi, PT, P)...")
        elif "E" in kinematic_vars and "P" not in kinematic_vars:
            combined_vars = ["Eta", "Phi", "E", "ET"]
            print("\n  Creating combined kinematic plot (Eta, Phi, E, ET)...")
        elif "P" in kinematic_vars and "E" in kinematic_vars:
            # EFlow or GenParticle - has both P and E
            combined_vars = ["Eta", "Phi", "PT", "E"]
            print("\n  Creating combined kinematic plot (Eta, Phi, PT, E)...")
        else:
            combined_vars = kinematic_vars[:4]  # Take first 4 variables
            print(f"\n  Creating combined kinematic plot ({', '.join(combined_vars)})...")

        # Create figure with 2 rows (histogram + ratio) and 4 columns (one per variable)
        fig = plt.figure(figsize=(30, 6))

        for idx, var in enumerate(combined_vars):
            torch_key = f"{branch_name}/{branch_name}.{var}"
            benchmark_key = f"{branch_name}/{branch_name}.{var}"

            if torch_key not in torch_tree or benchmark_key not in benchmark_tree:
                continue

            try:
                # Load data
                torch_data_events = torch_tree[torch_key].array()  # pyright: ignore[reportAttributeAccessIssue]
                benchmark_data_events = benchmark_tree[benchmark_key].array()  # pyright: ignore[reportAttributeAccessIssue]

                # Handle single-event vs all-events mode
                if event_number is not None:
                    torch_data = torch_data_events[event_number]
                    benchmark_data = benchmark_data_events[event_number]
                else:
                    torch_data = ak.flatten(torch_data_events)
                    benchmark_data = ak.flatten(benchmark_data_events)

                # Convert to numpy
                torch_np = np.asarray(torch_data)
                benchmark_np = np.asarray(benchmark_data)

                # Create subplot with histogram on top, ratio below
                # Use 4 rows to match the 3:1 height ratio, columns for each variable
                gs = plt.GridSpec(  # pyright: ignore[reportPrivateImportUsage]
                    4,
                    4,
                    figure=fig,
                    hspace=0.05,
                    wspace=0.3,
                    height_ratios=[3, 1, 0, 0],
                )

                # Column position (0-3 for Eta, Phi, PT, P)
                col = idx

                # Histogram subplot (row 0, takes 3 units of height)
                ax_hist = fig.add_subplot(gs[0, col])
                # Ratio subplot (row 1, takes 1 unit of height)
                ax_ratio = fig.add_subplot(gs[1, col], sharex=ax_hist)

                # Determine bin range
                all_data = np.concatenate([torch_np, benchmark_np])
                if len(all_data) > 0:
                    bins = list(
                        np.linspace(np.percentile(all_data, 1), np.percentile(all_data, 99), 40)
                    )
                else:
                    bins = 40

                # Plot histograms
                benchmark_hist = ax_hist.hist(
                    benchmark_np,
                    bins=bins,
                    histtype="stepfilled",
                    color="orange",
                    alpha=0.5,
                    linewidth=2,
                    label=f"C++ Delphes: {len(benchmark_np)} particles",
                    density=False,
                )
                torch_hist = ax_hist.hist(
                    torch_np,
                    bins=bins,
                    histtype="step",
                    color="blue",
                    linewidth=2,
                    label=f"Parnassus.TorchDelphes: {len(torch_np)} particles",
                    density=False,
                )
                benchmark_counts = np.asarray(benchmark_hist[0])
                bin_edges = np.asarray(benchmark_hist[1])
                torch_counts = np.asarray(torch_hist[0])

                ax_hist.set_ylabel("Counts", fontsize=11)
                ax_hist.set_title(f"{var}", fontsize=13, fontweight="bold")
                if idx == 0:  # Only show legend on first subplot
                    ax_hist.legend(fontsize=10)
                ax_hist.grid(True, alpha=0.3)
                ax_hist.tick_params(labelbottom=False)

                # Plot ratio
                bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
                ratio = np.divide(
                    torch_counts,
                    benchmark_counts,
                    out=np.ones_like(torch_counts),
                    where=benchmark_counts > 0,
                )

                ax_ratio.axhline(y=1.0, color="orange", linewidth=2)
                ax_ratio.plot(bin_centers, ratio, color="blue", markersize=3, linewidth=2)
                ax_ratio.set_xlabel(var, fontsize=11)
                ax_ratio.set_ylabel("Torch/C++", fontsize=9)
                ax_ratio.set_ylim(0.9 * min(ratio), 1.1 * max(ratio))
                ax_ratio.grid(True, alpha=0.3)

            except Exception as e:  # noqa: BLE001
                print(f"    ✗ Error plotting {var} in combined plot: {e}")
                continue

        # Add overall title
        suptitle = f"{branch_name}"
        if event_number is not None:
            suptitle = f"Event {event_number}: {suptitle}"
        fig.suptitle(suptitle, fontsize=16, fontweight="bold", y=0.98)

        # Save combined figure
        combined_plot_file = branch_dir / "all.png"
        plt.savefig(combined_plot_file, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  ✓ Combined plot saved → {combined_plot_file.name}")

        # 3. PID-specific combined plots (only for branches with PID field)
        # Skip if --validate-pid not specified
        if not validate_pid:
            continue

        torch_pid_key = f"{branch_name}/{branch_name}.PID"
        benchmark_pid_key = f"{branch_name}/{branch_name}.PID"

        if torch_pid_key in torch_tree and benchmark_pid_key in benchmark_tree:
            # Load PID data to get unique PIDs
            torch_pids = torch_tree[torch_pid_key].array()  # pyright: ignore[reportAttributeAccessIssue]
            benchmark_pids = benchmark_tree[benchmark_pid_key].array()  # pyright: ignore[reportAttributeAccessIssue]

            # Get unique PIDs (handle single-event vs all-events mode)
            if event_number is not None:
                torch_pids_flat = torch_pids[event_number]
                benchmark_pids_flat = benchmark_pids[event_number]
            else:
                torch_pids_flat = ak.flatten(torch_pids)
                benchmark_pids_flat = ak.flatten(benchmark_pids)
            unique_pids = np.unique(
                np.concatenate([np.asarray(torch_pids_flat), np.asarray(benchmark_pids_flat)])
            )

            # For each unique PID, create a combined plot
            for pid in unique_pids:
                pid_int = int(pid)

                # Create figure with 2 rows (histogram + ratio) and 4 columns (one per variable)
                fig = plt.figure(figsize=(30, 6))

                for idx, var in enumerate(combined_vars):
                    torch_key = f"{branch_name}/{branch_name}.{var}"
                    benchmark_key = f"{branch_name}/{branch_name}.{var}"

                    if torch_key not in torch_tree or benchmark_key not in benchmark_tree:
                        continue

                    # Load data (event-wise, not flattened yet)
                    torch_data_events = torch_tree[torch_key].array()  # pyright: ignore[reportAttributeAccessIssue]
                    benchmark_data_events = benchmark_tree[benchmark_key].array()  # pyright: ignore[reportAttributeAccessIssue]

                    # Filter by PID
                    torch_pid_events = torch_tree[torch_pid_key].array()  # pyright: ignore[reportAttributeAccessIssue]
                    benchmark_pid_events = benchmark_tree[benchmark_pid_key].array()  # pyright: ignore[reportAttributeAccessIssue]

                    # Handle single-event vs all-events mode
                    if event_number is not None:
                        # Single event: filter within that event
                        torch_data_event = torch_data_events[event_number]
                        benchmark_data_event = benchmark_data_events[event_number]
                        torch_pid_event = torch_pid_events[event_number]
                        benchmark_pid_event = benchmark_pid_events[event_number]

                        torch_data_filtered = np.asarray(torch_data_event)[
                            np.asarray(torch_pid_event) == pid
                        ]
                        benchmark_data_filtered = np.asarray(benchmark_data_event)[
                            np.asarray(benchmark_pid_event) == pid
                        ]
                    else:
                        # All events: apply PID mask and flatten
                        torch_data_filtered = ak.flatten(torch_data_events[torch_pid_events == pid])
                        benchmark_data_filtered = ak.flatten(
                            benchmark_data_events[benchmark_pid_events == pid]
                        )

                    # Convert to numpy
                    torch_np = np.asarray(torch_data_filtered)
                    benchmark_np = np.asarray(benchmark_data_filtered)

                    # Skip if no data for this PID
                    if len(torch_np) == 0 and len(benchmark_np) == 0:
                        continue

                    # Create subplot with histogram on top, ratio below
                    gs = plt.GridSpec(  # pyright: ignore[reportPrivateImportUsage]
                        4,
                        4,
                        figure=fig,
                        hspace=0.05,
                        wspace=0.3,
                        height_ratios=[3, 1, 0, 0],
                    )

                    # Column position (0-3 for variables)
                    col = idx

                    # Histogram subplot (row 0, takes 3 units of height)
                    ax_hist = fig.add_subplot(gs[0, col])
                    # Ratio subplot (row 1, takes 1 unit of height)
                    ax_ratio = fig.add_subplot(gs[1, col], sharex=ax_hist)

                    # Determine bin range
                    all_data = np.concatenate([torch_np, benchmark_np])
                    if len(all_data) > 0:
                        bins = list(
                            np.linspace(np.percentile(all_data, 1), np.percentile(all_data, 99), 40)
                        )
                    else:
                        bins = 40

                    # Plot histograms
                    benchmark_hist = ax_hist.hist(
                        benchmark_np,
                        bins=bins,
                        histtype="stepfilled",
                        color="orange",
                        alpha=0.5,
                        linewidth=2,
                        label=f"C++ Delphes, {len(benchmark_np)} particles",
                        density=False,
                    )
                    torch_hist = ax_hist.hist(
                        torch_np,
                        bins=bins,
                        histtype="step",
                        color="blue",
                        linewidth=2,
                        label=f"Parnassus.TorchDelphes, {len(torch_np)} particles",
                        density=False,
                    )
                    benchmark_counts = np.asarray(benchmark_hist[0])
                    bin_edges = np.asarray(benchmark_hist[1])
                    torch_counts = np.asarray(torch_hist[0])

                    ax_hist.set_ylabel("Counts", fontsize=11)
                    ax_hist.set_title(f"{var}", fontsize=13, fontweight="bold")
                    if idx == 0:  # Only show legend on first subplot
                        ax_hist.legend(fontsize=10)
                    ax_hist.grid(True, alpha=0.3)
                    ax_hist.tick_params(labelbottom=False)

                    # Plot ratio
                    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
                    ratio = np.divide(
                        torch_counts,
                        benchmark_counts,
                        out=np.ones_like(torch_counts),
                        where=benchmark_counts > 0,
                    )

                    ax_ratio.axhline(y=1.0, color="orange", linewidth=2)
                    ax_ratio.plot(bin_centers, ratio, color="blue", markersize=3, linewidth=2)
                    ax_ratio.set_xlabel(var, fontsize=11)
                    ax_ratio.set_ylabel("Torch/C++", fontsize=9)
                    ax_ratio.set_ylim(0.9 * min(ratio), 1.1 * max(ratio))
                    ax_ratio.grid(True, alpha=0.3)

                # Add overall title with PID
                suptitle = f"{branch_name} (PID={pid_int})"
                if event_number is not None:
                    suptitle = f"Event {event_number}: {suptitle}"
                fig.suptitle(suptitle, fontsize=16, fontweight="bold", y=0.98)

                # Save PID-specific combined figure
                pid_plot_file = branch_dir / f"pid_{pid_int}.png"
                plt.savefig(pid_plot_file, dpi=150, bbox_inches="tight")
                plt.close()

        else:
            print("  i No PID field - skipping PID-specific plots (normal for Tower objects)")

    print(f"\n{'=' * 70}")
    if event_number is not None:
        print(f"✓ Event {event_number} validation complete! Plots saved to {output_dir}")
    else:
        print(f"✓ Validation complete! Plots saved to {output_dir}")
    print(f"{'=' * 70}")


def main(
    input_file: str | Path,
    output_file: str | Path,
    benchmark_file: str | Path,
    validation_dir: Path,
    detector: str,
    max_events: int | None = None,
    batch_size: int = 100,
    debug: bool = False,
) -> None:
    """Main processing function.

    Parameters
    ----------
        input_file: Path to input HepMC file
        output_file: Path to output ROOT file
        benchmark_file: Path to benchmark ROOT file
        max_events: Maximum number of events to process (None = all)
        batch_size: Number of events per DataLoader batch
        debug: Passed through to the detector card for intermediate output
    """
    log = setup_logger()

    log.info(f"\nInput:  {input_file}")
    log.info(f"Batch size: {batch_size} events")
    log.info(f"Device: {DEVICE}")

    # -------------------------------------------------------------------------
    # 1. Load HepMC via dataset stack
    # -------------------------------------------------------------------------
    raw = HepMCDataset(input_file, num_events=max_events)
    dataset = ParametricAdapter(raw)
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        collate_fn=parametric_collate_fn,
    )
    log.info(f"Loaded {len(dataset)} events from HepMC.")

    # -------------------------------------------------------------------------
    # 2. Run detector simulation via ParametricEventGenerator
    # -------------------------------------------------------------------------
    config = ParametricGeneratorConfig(name=detector, card=detector.lower(), debug=True)
    generator = ParametricEventGenerator(config, log)
    generator.to(torch.device(DEVICE))

    with generator:
        generator.initialize(n_events=len(dataset), n_batches=len(dataloader))
        for batch in dataloader:
            generator.process_batch(batch)
        events = generator.get_events()

    log.info(f"Generated {len(events)} events.")
    accessors = generator.get_accessors()

    # -------------------------------------------------------------------------
    # 3. Write output via RootWriter
    # -------------------------------------------------------------------------
    accessor_store = AccessorStore.from_dict(accessors)
    writer = RootWriter(WriterConfig(file_path=output_file, accessor_store=accessor_store))
    writer.write(events)
    log.info(f"Output written to {output_file}.")

    # -------------------------------------------------------------------------
    # 4. Validate against C++ Delphes benchmark (if available)
    #
    # Note: validate_against_benchmark reads a Delphes-format ROOT tree.  The
    # RootWriter above produces a Parnassus-format tree, so the comparison only
    # makes sense when a separately-generated Delphes-format file is supplied
    # alongside a matching benchmark.  Skip silently when unavailable.
    # -------------------------------------------------------------------------
    if Path(benchmark_file).exists():
        log.info(f"Benchmark file: {benchmark_file}")
        log.info(f"Validation directory: {validation_dir}")
        validate_against_benchmark(output_file, benchmark_file, validation_dir, debug=debug)
    else:
        log.warning(f"Benchmark file not found: {benchmark_file} — skipping validation.")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns
    -------
        argparse.Namespace: Parsed arguments
    """
    parser = argparse.ArgumentParser(description="Parnassus TorchDelphes HepMC Processing")
    parser.add_argument(
        "--num-events",
        "-n",
        type=int,
        default=1_000,
        help="Maximum number of events to process (default: 1000)",
    )
    parser.add_argument(
        "--process",
        "-proc",
        type=str,
        default="HZZ4l",
        choices=["HZZ4l"],
        help="Process to simulate (default: HZZ4l)",
    )
    parser.add_argument(
        "--detector",
        "-det",
        type=str,
        default="CMS",
        choices=["CMS", "ATLAS"],
        help="Detector configuration to use (default: CMS)",
    )
    parser.add_argument(
        "--batch-size",
        "-bs",
        type=int,
        default=100,
        help="Number of events per batch (default: 100)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Print histogram bin counts and edges for debugging",
    )
    parser.add_argument(
        "--specific-event",
        type=int,
        default=None,
        help=(
            "Validate a specific event by index (0-based). "
            "If not set, validates all events aggregated."
        ),
    )
    parser.add_argument(
        "--skip-gen",
        action="store_true",
        help=(
            "Skip Torch generation and ROOT writing, jump directly to validation "
            "(requires existing output file)"
        ),
    )
    parser.add_argument(
        "--validate-pid",
        action="store_true",
        help=(
            "Create PID-specific combined plots for each unique PID "
            "(can be slow for large datasets)"
        ),
    )
    return parser.parse_args()


def _get_paths(args, script_dir: Path) -> tuple[Path, Path, Path, Path]:
    data_process_dir = script_dir / "data" / args.process
    data_detector_dir = data_process_dir / args.detector

    validation_dir = script_dir / "validation_plots" / args.process / args.detector
    validation_dir.mkdir(parents=True, exist_ok=True)

    if args.num_events <= 100:
        input_fpath = data_process_dir / f"{args.process}_100.hepmc"
        output_fpath = data_detector_dir / f"{args.process}_100_eflow_torch.root"
        benchmark_fpath = data_detector_dir / f"{args.process}_100_eflow.root"
    elif args.num_events <= 1_000:
        input_fpath = data_process_dir / f"{args.process}_1k.hepmc"
        output_fpath = data_detector_dir / f"{args.process}_1k_eflow_torch.root"
        benchmark_fpath = data_detector_dir / f"{args.process}_1k_eflow.root"
    elif args.num_events <= 10_000:
        input_fpath = data_process_dir / f"{args.process}_10k.hepmc"
        output_fpath = data_detector_dir / f"{args.process}_10k_eflow_torch.root"
        benchmark_fpath = data_detector_dir / f"{args.process}_10k_eflow.root"
    elif args.num_events <= 100_000:
        input_fpath = data_process_dir / f"{args.process}_100k.hepmc"
        output_fpath = data_detector_dir / f"{args.process}_100k_eflow_torch.root"
        benchmark_fpath = data_detector_dir / f"{args.process}_100k_eflow.root"
    else:
        raise ValueError(
            f"Unsupported number of events: {args.num_events}. Supported values: <= 100k."
        )

    return input_fpath, output_fpath, benchmark_fpath, validation_dir


if __name__ == "__main__":
    tic = time.time()
    args = parse_args()
    script_dir = Path(__file__).parent
    input_fpath, output_fpath, benchmark_fpath, validation_dir = _get_paths(args, script_dir)

    if args.skip_gen:
        if output_fpath.exists() and benchmark_fpath.exists():
            validate_against_benchmark(
                output_fpath,
                benchmark_fpath,
                validation_dir,
                debug=args.debug,
                event_number=args.specific_event,
                validate_pid=args.validate_pid,
            )
        else:
            print("\n⚠ Error: Output or benchmark file not found!")
            print(f"  Output: {output_fpath}")
            print(f"  Benchmark: {benchmark_fpath}")
            print(
                "  Please run the full pipeline first "
                "(without --skip-gen) to generate output files."
            )
    else:
        main(
            input_fpath,
            output_fpath,
            benchmark_fpath,
            validation_dir,
            detector=args.detector,
            max_events=args.num_events,
            batch_size=args.batch_size,
            debug=args.debug,
        )

        if args.specific_event is not None and output_fpath.exists() and benchmark_fpath.exists():
            validate_against_benchmark(
                output_fpath,
                benchmark_fpath,
                validation_dir,
                debug=args.debug,
                event_number=args.specific_event,
                validate_pid=args.validate_pid,
            )

    toc = time.time()
    dur = toc - tic
    print(f"\n{'=' * 80}")
    print(f"Total execution time on {DEVICE}: {dur // 60:.0f} minutes, {dur % 60:.2f} seconds")
    print(f"{'=' * 80}\n")
